apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: edockumentspublicapi
  description: edockumentspublicapi
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=edockumentspublicapi
  links:
    - title: "Container Logs"
      url: https://app.datadoghq.com/logs?query=service%edockumentspublicapi%20kube_namespace%3Aedockuments
  tags:
    - netcore
spec:
  type: service
  lifecycle: production
  owner: edockuments
  system: platform
  providesApis:
    - edockumentspublicapi
  consumesApis:
    - shipmentgrpcapi
    - documentmanagementgrpcapi
    - configurationgrpcapi
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: edockumentspublicapi
  description: edockumentspublicapi
spec:
  type: openapi
  lifecycle: production
  owner: edockuments
  definition:
    $text: https://api.dev.kbxt.cloud/public/edockuments/publicapi/swagger/v1.0/swagger.json
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shipmentgrpcapi
  description: shipmentgrpcapi
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=shipmentgrpcapi
  links:
    - title: "Container Logs"
      url: https://app.datadoghq.com/logs?query=service%3Ashipmentgrpcapi%20kube_namespace%3Aedockuments
  tags:
    - netcore
    - grpc
spec:
  type: service
  lifecycle: production
  owner: edockuments
  system: platform
  providesApis:
    - shipmentgrpcapi
  consumesApis:
    - configurationgrpcapi
  dependsOn: ['resource:shipmentgrpcapi-mongodb']
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: shipmentgrpcapi-mongodb
  description: shipmentgrpcapi-mongodb
spec:
  type: database
  lifecycle: production
  owner: platform
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: shipmentgrpcapi
  description: shipmentgrpcapi
spec:
  type: grpc
  lifecycle: production
  owner: edockuments
  definition: "Placeholder text"
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: documentmanagementgrpcapi
  description: documentmanagementgrpcapi
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=documentmanagementgrpcapi
  links:
    - title: "Container Logs"
      url: https://app.datadoghq.com/logs?query=service%3Adocumentmanagementgrpcapi%20kube_namespace%3Aedockuments
  tags:
    - netcore
    - grpc
spec:
  type: service
  lifecycle: production
  owner: platform
  system: platform
  providesApis:
    - documentmanagementgrpcapi
  consumesApis:
    - configurationgrpcapi
  dependsOn: ['resource:documentmanagementgrpcapi-mongodb']
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: documentmanagementgrpcapi-mongodb
  description: documentmanagementgrpcapi-mongodb
spec:
  type: database
  lifecycle: production
  owner: platform
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: documentmanagementgrpcapi
  description: documentmanagementgrpcapi
spec:
  type: grpc
  lifecycle: production
  owner: platform
  definition: "Placeholder text"
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: configurationgrpcapi
  description: configurationgrpcapi
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=configurationgrpcapi
  links:
    - title: "Container Logs"
      url: https://app.datadoghq.com/logs?query=service%3Aconfigurationgrpcapi%20kube_namespace%3Aedockuments
  tags:
    - netcore
    - grpc
spec:
  type: service
  lifecycle: production
  owner: platform
  system: platform
  providesApis:
    - configurationgrpcapi
  dependsOn: ['resource:configurationgrpcapi-sql-server']
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: configurationgrpcapi
  description: configurationgrpcapi
spec:
  type: grpc
  lifecycle: production
  owner: platform
  definition: "Placeholder text"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: configurationgrpcapi-sql-server
  description: configurationgrpcapi-sql-server
spec:
  type: database
  lifecycle: production
  owner: platform
