apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kbxtecho
  description: Kbxt Echo Service
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=kbxtecho
  tags:
    - netcore
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: platform
  providesApis:
    - kbxtecho
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: kbxtecho
  description: Kbxt Echo Service
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  definition:
    $text: https://api.dev.kbxt.cloud/public/echo/echo/swagger/v1.0/swagger.json
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kbxtechogrpc
  description: Kbxt Echo Grpc Service
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=kbxtechogrpc
  tags:
    - netcore
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: platform
