apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kbxtecho
  description: Kbxt Echo Service
  annotations:
    backstage.io/kubernetes-id: kbxtecho
  tags:
    - netcore
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: kbxtecho
